package serialize

import (
	"strings"

	"github.com/lex00/wetwire-github-go/codeowners"
)

// CodeownersToText serializes an Owners config to CODEOWNERS text format.
// CODEOWNERS format is: pattern owner1 owner2 ...
// Comments can be added with # prefix.
func CodeownersToText(o *codeowners.Owners) ([]byte, error) {
	var lines []string

	// Add header comment
	lines = append(lines, "# CODEOWNERS file generated by wetwire-github")
	lines = append(lines, "# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners")
	lines = append(lines, "")

	for _, rule := range o.Rules {
		// Add comment if present
		if rule.Comment != "" {
			lines = append(lines, "# "+rule.Comment)
		}

		// Format: pattern owner1 owner2 ...
		if len(rule.Owners) > 0 {
			line := rule.Pattern + " " + strings.Join(rule.Owners, " ")
			lines = append(lines, line)
		} else {
			// Pattern without owners (matches but no one is assigned)
			lines = append(lines, rule.Pattern)
		}
	}

	// Add trailing newline
	lines = append(lines, "")

	return []byte(strings.Join(lines, "\n")), nil
}

// CodeownersRulesToText serializes a slice of extracted rules to CODEOWNERS text format.
func CodeownersRulesToText(rules []ExtractedCodeownersRule) ([]byte, error) {
	var lines []string

	// Add header comment
	lines = append(lines, "# CODEOWNERS file generated by wetwire-github")
	lines = append(lines, "# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners")
	lines = append(lines, "")

	for _, rule := range rules {
		// Add comment if present
		if rule.Comment != "" {
			lines = append(lines, "# "+rule.Comment)
		}

		// Format: pattern owner1 owner2 ...
		if len(rule.Owners) > 0 {
			line := rule.Pattern + " " + strings.Join(rule.Owners, " ")
			lines = append(lines, line)
		} else {
			// Pattern without owners
			lines = append(lines, rule.Pattern)
		}
	}

	// Add trailing newline
	lines = append(lines, "")

	return []byte(strings.Join(lines, "\n")), nil
}

// ExtractedCodeownersRule mirrors the runner.ExtractedCodeownersRule for serialization.
type ExtractedCodeownersRule struct {
	Pattern string
	Owners  []string
	Comment string
}
